### ISSUE TITLE
run evaluate.py

### ISSUE THREAD

**Issue by caozhengtao110** [lppllppl920/EndoscopyDepthEstimation-Pytorch#10]
I'm sorry to bother you ,but I have a problem and need your help.

--sequence_root "/path/to/sequence/path"   --evaluation_data_root "/path/to/testing/data" --phase "test"

How do I find the two paths above? I can't find the test data. I tried to run the training dataset as a test dataset,and
the file name  " example_training_data_root"  to " test_path"  
The following file is the result of my run.

It is a great honor to communicate with you! Looking froward to your reply! 

 (my_environment) siat@siat-ThinkStation-P300:~/EndoscopyDepthEstimation-Pytorch-master2$ python evaluate.py --id_range 1 2 --adjacent_range 5 30 --input_size 256 320 --load_all_frames --load_intermediate_data --architecture_summary --sequence_root "/home/siat/EndoscopyDepthEstimation-Pytorch-master2/example_training_data_root/bag_1/_start_004259_end_004629_stride_25_segment_13" --evaluation_result_root "/home/siat/EndoscopyDepthEstimation-Pytorch-master2/test_result" --evaluation_data_root "/home/siat/EndoscopyDepthEstimation-Pytorch-master2/test_path/" --phase "test"
Tensorboard visualization at /home/siat/EndoscopyDepthEstimation-Pytorch-master2/test_result/depth_estimation_evaluation_run_6_24_15_55_test_id_N_o_n_e
----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
================================================================
            Conv2d-1         [-1, 48, 256, 320]           1,344
       BatchNorm2d-2         [-1, 48, 256, 320]              96
             .....
          Conv2d-178         [-1, 12, 256, 320]          19,452
      DenseBlock-179        [-1, 192, 256, 320]               0
          Conv2d-180          [-1, 1, 256, 320]             193
      FCDenseNet-181          [-1, 1, 256, 320]               0
================================================================
Total params: 1,374,865
Trainable params: 1,374,865
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.94
Forward/backward pass size (MB): 2579.58
Params size (MB): 5.24
Estimated Total Size (MB): 2585.76
----------------------------------------------------------------
Loading /home/siat/EndoscopyDepthEstimation-Pytorch-master2/depth_estimation_train_run_6_22_20_17_test_id_[_1_]/checkpoint_model_epoch_100_validation_0.09037257875833246.pt ...
Restored model, epoch 101, step 101000
  0%|                                                                                                                                                                                                      | 0/35 [00:00<?, ?it/s]Traceback (most recent call last):
  File "evaluate.py", line 323, in <module>
    for batch, (colors_1, boundaries, intrinsics, names) in enumerate(test_loader):
  File "/home/siat/anaconda3/envs/my_environment/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/siat/anaconda3/envs/my_environment/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/siat/anaconda3/envs/my_environment/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/siat/EndoscopyDepthEstimation-Pytorch-master2/dataset.py", line 470, in __getitem__
    start_h, end_h, start_w, end_w = self.crop_positions_per_seq[folder]
KeyError: '/home/siat/EndoscopyDepthEstimation-Pytorch-master2/example_training_data_root/bag_1/_start_004259_end_004629_stride_25_segment_13'
  0%|

**Comment by lppllppl920** [comment]
It is complaining about the intermediate data does not have the str '/home/siat/EndoscopyDepthEstimation-Pytorch-master2/example_training_data_root/bag_1/_start_004259_end_004629_stride_25_segment_13' as a key. You may need to look into it to see where you have stored that intermediate data and whether or not the stated path is actually in the dictionary.

**Comment by caozhengtao110** [comment]
After training, I got a folder:depth_estimation_train_run_6_22_20_17_test_id_[_1_]
This folder contains: Training  folder,Validation folder, all_scalars_0-100.json ,checkpoint_model_epoch_0-100_validation_0.08256435249414709.pt
What part do you mean by intermediate data?

Here is the path I specified:
--sequence_root "/path/to/sequence/path"  :/home/siat/EndoscopyDepthEstimation-Pytorch-master2/example_training_data_root/bag_1/_start_004259_end_004629_stride_25_segment_13

--evaluation_data_root "/path/to/testing/data"  : Instead of validating the data set, I used the trained data set

--trained_model_path "/path/to/trained/model"  :/home/siat/EndoscopyDepthEstimation-Pytorch-master2/depth_estimation_train_run_6_22_20_17_test_id_[_1_]/checkpoint_model_epoch_99_validation_0.09233879463540183.pt

Thank you for your help !

**Comment by lppllppl920** [comment]
The intermediate data is the one with prefix "precompute_". You can look into the initialization function of the dataset class to figure out the path of the intermediate data. It is generated to reduce the computation required during training data loading.

**Comment by caozhengtao110** [comment]
Thank you very much for your help. I will try this method.
