### ISSUE TITLE
Depth map and 3D reconstruction

### ISSUE THREAD

**Issue by caozhengtao110** [lppllppl920/EndoscopyDepthEstimation-Pytorch#12]
hello!
How can I get the final depth map and 3D reconstruction results from the data you gave me?
I have tried to adjust the training phase, will the test phase get the final result?
Looking forward to your reply! I hope to get your help.

**Comment by lppllppl920** [comment]
The 3D reconstruction result needs to be obtained by converting the dense depth map predicted from the network to a 3D point cloud. It requires camera intrinsic matrix as an additional input.
