### ISSUE TITLE
view size is not compatible with input tensor's size and stride

### ISSUE THREAD

**Issue by YanhaoZhang** [lppllppl920/EndoscopyDepthEstimation-Pytorch#13]
Hi. Thank you very much for releasing the code.

I am running the code with the example data with the batch_size as 4 and other parameters as what is shown in the document. May I ask you if you have any suggestions for the following issue? Many thanks.

 Epoch 0, lr [0.0001]:   0%|                                                                                                                                    | 0/2000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 307, in <module>
    intrinsics])
  File "/data/yanhzhan/anaconda_y/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/yanhzhan/YhZ_ICRA2021/EndoscopyDepthEstimation-Pytorch-master/models.py", line 463, in forward
    rotation_matrices, intrinsic_matrices, self.epsilon)
  File "/data/yanhzhan/YhZ_ICRA2021/EndoscopyDepthEstimation-Pytorch-master/models.py", line 541, in _depth_warping
    u_2_flat = u_2.view(-1)
**RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.**
Exception ignored in: <object repr() failed>

**Comment by lppllppl920** [comment]
It seems like the functionality of view() and reshape() has changed. Simply replacing view() with reshape() should work.

**Comment by YanhaoZhang** [comment]
Thanks for your reply. I replaced view to reshape and it works. :+1:
