### ISSUE TITLE
will grey-scale images also work?

### ISSUE THREAD

**Issue by YanhaoZhang** [lppllppl920/EndoscopyDepthEstimation-Pytorch#14]
Hi. May I ask if this code also works with grey-scale images? Or may I ask any suggestions on how to modify the code to fit with the grey-scale image?

**Comment by lppllppl920** [comment]
I think it will work. You just need to make sure to change the number of input channel of the network from 3 to 1. The dataset class may also need to be changed to use channel dimension 1 instead of 3.

**Comment by YanhaoZhang** [comment]
Got it. I will try this. Many thanks for your help.
