### ISSUE TITLE
duplicate code in dataset.py when calculating the largest required h and w

### ISSUE THREAD

**Issue by YanhaoZhang** [lppllppl920/EndoscopyDepthEstimation-Pytorch#16]
Hi @lppllppl920 I find that the following [code 191-206](https://github.com/lppllppl920/EndoscopyDepthEstimation-Pytorch/blob/65f850c3723bc56756161fe3809cf17ae68ef407/dataset.py#L191-L206) in dataset.py is a bit duplicated. May I ask if there are any special reasons? My understanding is that if there are multiple data folders, then `process_pool` stores the data, but why the outer loop is removed later?

**Comment by lppllppl920** [comment]
This is really just to make sure no data are still left in the queue. You can optimize it if you would like to. But since the intermediate data is only calculated once, it won't affect the data loading performance.

**Comment by YanhaoZhang** [comment]
Thanks @lppllppl920 Now I understand it.
