### ISSUE TITLE
Regarding to the reproducibility

### ISSUE THREAD

**Issue by ylwitan** [lppllppl920/EndoscopyDepthEstimation-Pytorch#17]
Hi, thanks for your job. I have a question about the code reproducibility.
In order to make results reproducible,  we must set two options about CuDNN, but there are some differences in your code and [PyTorch docs.](https://pytorch.org/docs/stable/notes/randomness.html#cudnn)
In your code, 

> `# Fix randomness for reproducibility`
`torch.backends.cudnn.deterministic = False`
`torch.backends.cudnn.benchmark = True`

But in PyTorch docs, 

> `torch.backends.cudnn.deterministic = True`
`torch.backends.cudnn.benchmark = False`

Could you please tell me why?

**Comment by lppllppl920** [comment]
These two terms actually have minimal effect on its reproducibility. The main thing that will affect it is the seeds of the random number generator. You can change it the what Pytorch doc says.
