### ISSUE TITLE
about dense depth

### ISSUE THREAD

**Issue by YanhaoZhang** [lppllppl920/EndoscopyDepthEstimation-Pytorch#18]
Hi @lppllppl920, I am wondering if you could explain a bit more on how to get a dense depth map? 
 - Is the result of the monocular Depth Estimation Layer a dense depth?
 - If not, how to get the depth of the grid-mesh (U,V) for the Flow from Depth Layer?
Many thanks.

**Comment by lppllppl920** [comment]
Hi Yanhao,

Yes, the output of the depth estimation layer is a dense depth map. It is later on used in the Flow from Depth layer to generate rigid flow map together with other forms of data.

**Comment by YanhaoZhang** [comment]
Thanks @lppllppl920. Now I understand it.
