### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape' in get_color_imgs() and get_pair_color_imgs()

### ISSUE THREAD

**Issue by Harish238** [lppllppl920/EndoscopyDepthEstimation-Pytorch#2]
Getting this error when trying to run the code with the given training data. Turns out that the crop_positions are faulty, with start_h = end_h and start_w = end_w, making the crop area = 0.

**Comment by lppllppl920** [comment]
I'm sorry for the inconvenience. I have now updated the scripts and it should now work with only one folder which begins with the name "_start".
