### ISSUE TITLE
sparse soft mask

### ISSUE THREAD

**Issue by YanhaoZhang** [lppllppl920/EndoscopyDepthEstimation-Pytorch#20]
Hi @lppllppl920. From the paper, I read that a soft mask is applied. May I ask where it is applied in the code? I tested Mj in eq(6), and eq(10). It seems that the mask is a boolean variable. Many thanks.

**Comment by lppllppl920** [comment]
Hi Yanhao,

The mask used in the code is indeed a binary mask. The soft assignment was used previously to reduce the impact of extreme outliers and it is now relied on a pre-processing algorithm to first remove these.

**Comment by YanhaoZhang** [comment]
Hi @lppllppl920 Many thanks for your explanation.
