### ISSUE TITLE
a small update of read_point_cloud

### ISSUE THREAD

**Issue by YanhaoZhang** [lppllppl920/EndoscopyDepthEstimation-Pytorch#24]
Hi, I find there should be a small update of function read_point_cloud. I replaced [these lines]( https://github.com/lppllppl920/EndoscopyDepthEstimation-Pytorch/blob/6ec08d3e7c81ba65b1cb76affa00c53ee4868db0/utils.py#L204-L209) with 
```python
temp_xyz = [temp[0], temp[1], temp[2], 1.0]
lists_3D_points.append(temp_xyz)
```

**Comment by lppllppl920** [comment]
Thanks!

**Comment by YanhaoZhang** [comment]
No worries :)
