### ISSUE TITLE
Try a new data set

### ISSUE THREAD

**Issue by caozhengtao110** [lppllppl920/EndoscopyDepthEstimation-Pytorch#25]
Dear Author：
    Follow the requirements in your readme.md. If you change to a new data set, I need to preprocess the data set. I need to get motion.yaml through SFM or SLAM. In addition, there are camera_intrinsics_per_view, selected_indexes,visible_view_indexes
Do I need to get structure.ply before I train? Does it represent the reconstruction result of one frame or the reconstruction result of multiple frames?

**Comment by lppllppl920** [comment]
Hi Zhengtao,

Yes, you need to get the data like the format here yourself. structure.ply is generated from SFM or SLAM.

**Comment by YanhaoZhang** [comment]
Hi @lppllppl920, I think it might be good to mention that the pose definition from colmap is from world to camera, while in your code, it is from camera to world. Just in case someone else is going to use colmap to preprocess the image.

**Comment by caozhengtao110** [comment]
Thank you for the author and Thank you  for friend

**Comment by qqc222111** [comment]
> Hi @lppllppl920, I think it might be good to mention that the pose definition from colmap is from world to camera, while in your code, it is from camera to world. Just in case someone else is going to use colmap to preprocess the image.

So what should I do if I use colmap to preprocess the data in order to generate correct depth map
