### ISSUE TITLE
Questions about README.me

### ISSUE THREAD

**Issue by caozhengtao110** [lppllppl920/EndoscopyDepthEstimation-Pytorch#26]
Hello, dear author, I have two files that I don’t understand well, I hope to get your help!

camer_intrinsics_per_view 
Can you explain in detail what the three rows of numbers in camera_intrinsics_per_view mean? 

view_indexes_per_point 
How is the view_indexes_per_point file obtained?Does he indicate which frames of images are obtained from each 3D point?  If I try a new data set, how do I get it? what is the purpose of this file?

**Comment by lppllppl920** [comment]
camer_intrinsics_per_view stores f, cx, and cy. I remember that I have updated the related code so that it has four numbers per camera now, which makes it become fx, fy, cx, and cy. It just means an assumption of the pinhole camera model.

**Comment by caozhengtao110** [comment]
Thanks to the author for his help
