### ISSUE TITLE
Flow from Depth Layer

### ISSUE THREAD

**Issue by lalithnag** [lppllppl920/EndoscopyDepthEstimation-Pytorch#27]
Hi Authors, thanks for your nice work! In your paper, I wasn't able to understand how you arrived at Eq. (7). for U_k and V_k. In particular, why is A=K,R_j ^k.K^-1 and B=-K.t_j^k. (Similarly for Eq. 9).
It would be super helpful if you could explain it further or direct me towards some resources to understand the same.
Thanks in advance!

**Comment by YanhaoZhang** [comment]
Hi @lalithnag. I think it is from the following equation, but I did not proof it very carefully. I find some more details (eq.2) in [this paper](https://people.eecs.berkeley.edu/~tinghuiz/projects/SfMLearner/). 
![image](https://user-images.githubusercontent.com/36495922/89114153-a11a0a80-d4bc-11ea-980e-4e09591f7014.png)
