### ISSUE TITLE
Verification set

### ISSUE THREAD

**Issue by resindraburiza** [lppllppl920/EndoscopyDepthEstimation-Pytorch#3]
Hello, 
first of all, thank you for sharing the code to the public.

I tried your code and, even though I had to make some modification, I can run the training phase without any problem. But, there is no validation set to validate the training result. Is it possible for you to provide a validation set too? Or, did I do something wrong? Can the validation also be done using the data in this repository? 

Thank you so much.

**Comment by resindraburiza** [comment]
Also, I have an additional question.

When I run teacher_training.py, I got this result:
```
Epoch 4, lr [0.00011080000000000001]: 100%|█| 40/40 [00:03<00:00,  8.06it/s, loss=20.90089 15.47590, loss_depth_consistency=8.06786 9.90660, loss_scale_std=6.74215 2.22112, loss_sparse_flow=6.09088 3.34819]('Failure sequences: ', {'example_training_data_root/bag_1/_start_004259_end_004629_stride_25_segment_13/': 1})
Number of failure sequences: 1
```
what does it mean? Does it mean the training was not successfully done? Why is it so? Thank you very much.

**Comment by cyh4520** [comment]
> Also, I have an additional question.
> 
> When I run teacher_training.py, I got this result:
> 
> ```
> Epoch 4, lr [0.00011080000000000001]: 100%|█| 40/40 [00:03<00:00,  8.06it/s, loss=20.90089 15.47590, loss_depth_consistency=8.06786 9.90660, loss_scale_std=6.74215 2.22112, loss_sparse_flow=6.09088 3.34819]('Failure sequences: ', {'example_training_data_root/bag_1/_start_004259_end_004629_stride_25_segment_13/': 1})
> Number of failure sequences: 1
> ```
> 
> what does it mean? Does it mean the training was not successfully done? Why is it so? Thank you very much.

hi
i have some problem on the training phase. Can u help me.
when I run the training code as the author provides. It came to be

  File "/share/chyh/workspace/EndoscopyDepthEstimation-Pytorch/dataset.py", line 353, in __getitem__
    pair_extrinsic_matrices = [self.extrinsics_per_seq[folder][pos],
KeyError: 'example_training_data_root/bag_1/_start_004259_end_004629_stride_25_segment_13'

and my training script is 
python student_training.py --id_range 1 11 --input_downsampling 4.0 --network_downsampling 64 --adjacent_range 5 30 --torchsummary_input_size 256 320 --batch_size 2 --num_workers 8 --validation_interval 1 --display_interval 50 --dcl_weight 0.1 --sfl_weight 20.0 --max_lr 1.0e-3 --min_lr 1.0e-4 --inlier_percentage 0.99 --testing_patient_id 4 --load_intermediate_data --use_hsv_colorspace --number_epoch 2 --num_iter 100 --architecture_summary --training_result_root "result" --training_data_root example_training_data_root/

thank you very much

**Comment by lppllppl920** [comment]
I'm sorry for not responding to the issues in time. I have now fixed the issues related to running the training script. In terms of the validation set, because the sinus dataset is proprietary, we cannot share more data. I'm sorry for the inconvenience.
