### ISSUE TITLE
Invalid magic number

### ISSUE THREAD

**Issue by jamesmartin-46** [lppllppl920/EndoscopyDepthEstimation-Pytorch#30]
Hey please may I ask, when running evaluate.py i get this error...

"Invalid magic number; corrupt file?" when executing line "torch.load(str(trained_model_path))"  

the trained model path is to the example you supplied 'example_training_data_root/precompute_4.0_64_0.99.pkl' 

Any idea what may cause this error? thanks

**Comment by lppllppl920** [comment]
The pkl is the intermediate data for data loader. .pt is the actual model. I don’t think I provided the pretrained model though.

**Comment by jamesmartin-46** [comment]
Thanks so much, fixed.
