### ISSUE TITLE
problem about _depth_warping

### ISSUE THREAD

**Issue by XC9292** [lppllppl920/EndoscopyDepthEstimation-Pytorch#33]
Hi @lppllppl920 from eq(7) in the paper, B=-K*t, while in the code it seems to be B=-K*R.inv()*t. May I ask if it is because the pose is defined differently from the paper?

**Comment by lppllppl920** [comment]
Yes, R.inv()*t is the translation part of the inverse of the transformation [R, t]. The definition of camera poses is different.

**Comment by XC9292** [comment]
Thanks very much!
