### ISSUE TITLE
Stuck in validation

### ISSUE THREAD

**Issue by michel84** [lppllppl920/EndoscopyDepthEstimation-Pytorch#35]
Hello!

I am able to run the code for the first training epoch, but it gets stuck in validation. "Validation Epoch 0: 0%| | 0/36 [00:35<?, ?it/s]"

I tried to change the multiprocessor start processes to 'spawn' and 'fork' but I still get the same problem.

Any ideas in how to solve this issue?

Thank you very much in advance!

**Comment by lppllppl920** [comment]
Hi,

I encountered this problem before and solved it with the attempt you mentioned above. Not sure what causes this and let me know if you have found a solution to it.

Thanks!
