### ISSUE TITLE
num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by marinaoliveira** [lppllppl920/EndoscopyDepthEstimation-Pytorch#4]
Hello! Thank you so much for uploading the code. 
I am having some issues running the example provided in GitHub in the folder example_training_data_root/bag_1/_start_004259_end_004629_stride_25_segment_13. 

This is the command I used:
```python student_training.py --id_range 1 11 --input_downsampling 4.0 --network_downsampling 64 --adjacent_range 5 30 --torchsummary_input_size 256 320 --batch_size 8 --validation_interval 1 --display_interval 50 --dcl_weight 0.1 --sfl_weight 20.0 --max_lr 1.0e-3 --min_lr 1.0e-4 --inlier_percentage 0.99 --testing_patient_id 4 --load_intermediate_data --use_hsv_colorspace --number_epoch 100 --num_iter 1000 --architecture_summary --training_result_root "output" --training_data_root "example_training_data_root/bag_1/_start_004259_end_004629_stride_25_segment_13"```

This is the error I got:
```
Tensorboard visualization at output/depth_estimation_training_run_11_15_9_38_test_id_[4]
Traceback (most recent call last):
  File "student_training.py", line 182, in <module>
    num_workers=num_workers)
  File "/home/marina/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "/home/marina/.local/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
```

**Comment by cyh4520** [comment]
> Hello! Thank you so much for uploading the code.
> I am having some issues running the example provided in GitHub in the folder example_training_data_root/bag_1/_start_004259_end_004629_stride_25_segment_13.
> 
> This is the command I used:
> `python student_training.py --id_range 1 11 --input_downsampling 4.0 --network_downsampling 64 --adjacent_range 5 30 --torchsummary_input_size 256 320 --batch_size 8 --validation_interval 1 --display_interval 50 --dcl_weight 0.1 --sfl_weight 20.0 --max_lr 1.0e-3 --min_lr 1.0e-4 --inlier_percentage 0.99 --testing_patient_id 4 --load_intermediate_data --use_hsv_colorspace --number_epoch 100 --num_iter 1000 --architecture_summary --training_result_root "output" --training_data_root "example_training_data_root/bag_1/_start_004259_end_004629_stride_25_segment_13"`
> 
> This is the error I got:
> 
> ```
> Tensorboard visualization at output/depth_estimation_training_run_11_15_9_38_test_id_[4]
> Traceback (most recent call last):
>   File "student_training.py", line 182, in <module>
>     num_workers=num_workers)
>   File "/home/marina/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 213, in __init__
>     sampler = RandomSampler(dataset)
>   File "/home/marina/.local/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 94, in __init__
>     "value, but got num_samples={}".format(self.num_samples))
> ValueError: num_samples should be a positive integer value, but got num_samples=0
> ```

hi i met the same question too. have you already solved this problem？

**Comment by lppllppl920** [comment]
I apologize for the inconvenience. I have now fixed the bugs related to running training script with only one folder which begins with "_start". Let me know if there are still errors.
