### ISSUE TITLE
training data issue

### ISSUE THREAD

**Issue by cyh4520** [lppllppl920/EndoscopyDepthEstimation-Pytorch#6]
hi, I was preparing my training datas using COLMAP. And I transformed the format like yours. But the training result is not well. And the datas created by COLMAP is not as similar as yours.
I wanna ask what kind of the tool you use to create the datas?

**Comment by lppllppl920** [comment]
Please refer to the paper for the SfM method I used to create data. However, that method is not publicly available. One quick way to verify your SfM results is to project 3D sparse points onto image planes using the estimated camera trajectory. The projected 2D locations should be well locked onto features on the tissue surface.

**Comment by cyh4520** [comment]
thanks !
