### ISSUE TITLE
How do I run evaluate.py?

### ISSUE THREAD

**Issue by kimtaehyeong** [lppllppl920/EndoscopyDepthEstimation-Pytorch#8]
Hello,
I ended up learning student_training.py.
I want to see the output through evaluate.py. 
What should I do?

**Comment by lppllppl920** [comment]
You need to provide the path to the trained model, the path to your testing data, and other necessary settings. Please refer to the source code of evaluate.py for details.

**Comment by kimtaehyeong** [comment]
Thank you for your response.
I have two questions.

First, I want to evaluate through the training sample data you provided, but I wonder how to put the values ​​of the arguments for which the required is True. I would like some examples like student_training.py.

Secondly, I want to create another custom, but I'm curious what framework SfM used.

Thank you.

**Comment by leochan2009** [comment]
same here, would like to create custom model from my own data. Do you have the code for SFM?
Thanks!

**Comment by Zixin-YANG** [comment]
Same here, I am also curious about which sfm code you are using.

**Comment by lppllppl920** [comment]
I have added information on how to run evaluate.py and which work the SfM method is based on. Hope it can help you.
