### ISSUE TITLE
run train.py

### ISSUE THREAD

**Issue by caozhengtao110** [lppllppl920/EndoscopyDepthEstimation-Pytorch#9]
An error message appears at runtime：
AttributeError: 'SfMDataset' object has no attribute 'pre_workers'

Is it because of the lack of data set?
Can you provide a data set? 

I am looking forward to your reply. Wish you a happy life and good luck in your work！

**Comment by lppllppl920** [comment]
There was a bug in the dataset class where I did not change pre_workers to num_pre_workers. This argument specifies how many threads will be used to calculate intermediate data for network training. I did provide a small data example in this repo, therefore it may not be the problem of lack of data.

**Comment by lppllppl920** [comment]
Please update your code and let me know if there is any error.

**Comment by caozhengtao110** [comment]
I feel very lucky and excited to receive your reply！
I still get some errors when I run the code：

１．
Traceback (most recent call last):
  File "train.py", line 149, in <module>
    "_".join(testing_patient_id))
TypeError: sequence item 0: expected str instance, int found

２．
 Tensorboard visualization at depth_estimation_train_run_6_22_11_48_test_id_[_1_]
Traceback (most recent call last):
  File "train.py", line 172, in <module>
    rgb_mode="rgb", num_iter=num_iter)
  File "/home/siat/下载/EndoscopyDepthEstimation-Pytorch-master3/dataset.py", line 174, in __init__
    interval = len(self.folder_list) / self.num_pre_workers
ZeroDivisionError: division by zero

Thank you very much for forgiving my stupidity and giving me advice！

**Comment by caozhengtao110** [comment]
image size calculation failed.
Traceback (most recent call last):
  File "train.py", line 172, in <module>
    rgb_mode="rgb", num_iter=num_iter)
  File "/home/siat/EndoscopyDepthEstimation-Pytorch-master2/dataset.py", line 211, in __init__
    raise IOError
OSError

**Comment by caozhengtao110** [comment]
Thank you very much. The problem has been solved. I wrote the wrong path

**Comment by YanhaoZhang** [comment]
Hi @caozhengtao110, I also got the same error as follow. May I ask you how did you solve it? Thank you very much. 

> Traceback (most recent call last):
> File "train.py", line 149, in
> "_".join(testing_patient_id))
> TypeError: sequence item 0: expected str instance, int found

**Comment by caozhengtao110** [comment]
@YanhaoZhang 
str(testing_patient_id) 
You can try it,

**Comment by YanhaoZhang** [comment]
@caozhengtao110 Many thanks for your prompt reply!
